# Titanic survival predictor

___

In [1]:
import pandas as pd
from ml_algorithms import RandomForest

In [3]:
titanic_df = pd.read_csv('data/titanic_data.csv')
titanic_df.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,0,1,0,1,0.2750,0.014151,0,0,1,0.1,1,0,0,0,0,0,1
1,1,2,1,0,0.4750,0.139136,1,0,0,0.1,1,0,0,0,1,0,0
2,2,3,1,0,0.3250,0.015469,0,0,1,0.0,0,0,0,1,0,0,1
3,3,4,1,0,0.4375,0.103644,1,0,0,0.1,1,0,0,0,0,0,1
4,4,5,0,1,0.4375,0.015713,0,0,1,0.0,1,0,0,0,0,0,1

In [6]:
data = titanic_df[['Sex', 'Age', 'Fare', 'Family_size', 'Survived']]
data.head()

   Sex     Age      Fare  Family_size  Survived
0    1  0.2750  0.014151          0.1         0
1    0  0.4750  0.139136          0.1         1
2    0  0.3250  0.015469          0.0         1
3    0  0.4375  0.103644          0.1         1
4    1  0.4375  0.015713          0.0         0

In [7]:
test_split = int(len(data) * 0.8)
train_data = data[:test_split]
test_data = data[test_split:]

In [21]:
forest = RandomForest(40)
forest.fit_data(train_data.values)

In [24]:
predictions = forest.predict(test_data.values)
test_data['Prediction'] = predictions

C:\Users\jack0\AppData\Local\Temp\ipykernel_15636\2186494917.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data['Prediction'] = predictions

In [23]:
correct = test_data[test_data['Survived'] == test_data['Prediction']]

print(len(correct) / len(test_data))

0.8238993710691824